name: Tests

on: [push]

jobs:
  noop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Do nothing
      run: echo "This job does nothing."